inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - './vendor/**/*'
    - './node_modules/**/*'
    - './log/**/*'
    - './tmp/**/*'

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 150
  Enabled: true

Style/EmptyMethod:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false
